---
# Variables pour la cible HP Envy (Debian)
nginx_server_name: hellocyberworld.com

# Desactive la mise en veille quand le capot est ferme
hp_envy_disable_lid_suspend: true

# Sites markdown a deployer
markdown_sites:
  - name: julie
    domain: julie.hellocyberworld.com
    title: "Pour Julie"
    markdown_file: julie.md
    css_file: julie.css

# Certbot - certificats HTTPS
certbot_email: lucas@hellocyberworld.com
certbot_domains:
  - hellocyberworld.com
  - julie.hellocyberworld.com