#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/nginx
- name: Collecter la liste des services
  service_facts:

- name: Arreter Apache si present (conflit avec le port 80)
  service:
    name: apache2
    state: stopped
    enabled: no
  when: "'apache2.service' in ansible_facts.services"

- name: Installer Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copier la configuration Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart nginx

- name: S’assurer que Nginx est démarré
  service:
    name: nginx
    state: started
    enabled: yes

- name: Créer une page d'accueil personnalisée
  copy:
    content: '<h1>Hello from HelloCyberWorld!</h1><p>Kem, i love you!</p>'
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'