[dev]
192.168.56.10 ansible_user=vagrant ansible_private_key_file=../.vagrant/machines/default/virtualbox/private_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[raspberrypi]
192.168.1.190 ansible_user=lucas ansible_become=true ansible_become_method=sudo ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[hp_envy]
192.168.1.139 ansible_user=lucas ansible_become=true ansible_become_method=sudo ansible_ssh_common_args='-o StrictHostKeyChecking=no'